name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
      - name: Install backend deps
        run: |
          poetry install --no-interaction --no-root
      - name: Run pytest
        run: |
          poetry run pytest -q
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: npm install
        run: |
          cd frontend && npm install
      - name: Run npm tests
        run: |
          cd frontend && npm test --silent
      - name: Poetry check
        run: |
          poetry check
